### ISSUE TITLE
Add support for the per-frame DEFLATE extension

### ISSUE THREAD

**Issue by bendiy** [Automattic/socket.io#1148]
Any plans to add support for per-frame DEFLATE: http://tools.ietf.org/html/draft-tyoshino-hybi-websocket-perframe-deflate-06

Some basic tests suggest I could reduce the size of my message frames to just 12% of their original size.  That would help a lot with bandwidth usage.

Thanks!

**Comment by rustinlee** [comment]
Not that there's even a point to +1ing any more, but here you go anyway :+1:

**Comment by nhitchins** [comment]
+10000000

**Comment by rauchg** [comment]
Support for engine.io is almost ready. Sit tight!

**Comment by nhitchins** [comment]
awesome!

**Comment by leeus** [comment]
I see this has made it to the engine.io-client overnight, is there a way to try Socket.IO with this at all?  Would it be a case of forking and editing the package.json?

**Comment by rauchg** [comment]
Continuing this here:
https://github.com/Automattic/socket.io/issues/1947

We're about to merge the socket.io integration. At that point you can use it :)
