### ISSUE TITLE
socket.io parser.js crushes with "call stock is exceeded"

### ISSUE THREAD

**Issue by yuryb** [Automattic/socket.io#1560]
When trying to upgrade my website and (nodejs + express + socket.io) server from socket.io 0.9 to 1.0, immediatelly ran into the problem with the server - it crushes with the following exception: 

<path to my node code here>\node_modules\socket.io\node_modules\socket.io-parser\binary.js:98
  function removeBlobsRecursive(obj, curKey, containingObject) {
                               ^
RangeError: Maximum call stack size exceeded

Needless to say - everything is running FOR YEARS on socket.io 0.9 with no problems.
I do understand that this problem is hard to pinpoint without looking into my entire codebase, so i'm more reporting it here than expect some meaningful response.

My server code is not that complex, but there is some fairly large JSON payloads being sent from the server to the client. The crush happens, it looks like, when that JSON is being parsed.

Maybe some ideas?

PS: new version is great! Can't wait to have it working and stable...

**Comment by rase-** [comment]
Circular objects are tracked currently: https://github.com/Automattic/socket.io/issues/1524

**Comment by rase-** [comment]
Are you still experiencing these issues @yuryb?

**Comment by rase-** [comment]
We also have a test for large JSON emits: https://github.com/Automattic/socket.io/blob/master/test/socket.io.js#L1052

**Comment by rase-** [comment]
Closing for now, but feel free to reopen @yuryb, if problem persists.

**Comment by MarcGodard** [comment]
Sorry to renew this, but seem to be getting the same-ish issue...

```
ug 31 07:05:45Z swp-phase2-prod app/web.4 error: Unhandled Rejection at: [object Promise] reason: RangeError: Maximum call stack size exceeded
Aug 31 07:05:45Z swp-phase2-prod app/web.4 error: Stack:  Maximum call stack size exceeded {"stack":"RangeError: Maximum call stack size exceeded\n    at get (internal/bootstrap/pre_execution.js:309:8)\n    at isBuf (/app/node_modules/socket.io-parser/is-buffer.js:18:31)\n    at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:128:44)\n    at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)\n    at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)\n    at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)\n    at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)\n    at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)\n    at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)\n    at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)\n    at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)\n    at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)\n    at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)\n    at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)\n    at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)\n    at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)\n    at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)\n    at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)\n    at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)\n    at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)\n    at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)\n    at _removeBlobs (/app/node_modules/socket.io-parser/binary.js:130:9)"}
```
