### ISSUE TITLE
utf8 error

### ISSUE THREAD

**Issue by japrescott** [Automattic/socket.io#1561]
when updating from pre4 to 1.0.2 I suddenly got an "invalid utf-8 characters" error in chrome. I thought it must have something to do with the language (german) I'm sending down containing umlaute (ö,ä,ü). So I did en encodeURIComponent(JSON.stringify(object)) before sending it down and decodeURIComponent on the client and this fixed the issue.

Wanted to leave this here for others encountering the error and also for the team to look into it, as it previously worked like a charm without the en/decoding.

**Comment by rase-** [comment]
Alright, thanks for checking @sweetpi. Closing for now.
