### ISSUE TITLE
Custom event naming convention

### ISSUE THREAD

**Issue by ismarslomic** [Automattic/socket.io#1571]
What event naming conventions does socket.io project follow? I would like to reuse it for my custom events as well, in order to make the application.

**Comment by rase-** [comment]
Here are a few internal event name examples:
- `close`
- `packet`
- `packetCreate`
- `encoded`

Like @capaj mentioned, it's really up to you how you want to name them. A pretty common way is to not do camel case, but add whitespace, such as `new post`.
