### ISSUE TITLE
When connecting to a namespace instead of '/', messages sent immediatelly after connect get lost

### ISSUE THREAD

**Issue by capaj** [Automattic/socket.io#1573]
I have created a simple gist:
https://gist.github.com/capaj/d8c577599987bdd83d4b

where I have two server scripts and two HTML files. You can run that example by downloading, extracting and running npm install.

server_no_nsp.js runs as it should and logs the data coming from the client.
server_nsp.js runs but data from the client are not received on the server. Seems like they are not even sent from the client. When I use timeout for 20ms, then it works as it should. I guess connect event for custom namespaces is triggered too soon?

Please fix this.

just little bit about my environment: Win 8.1 64-bit, Node 0.10.28, browser Chrome 35

**Comment by rase-** [comment]
A fix for this merged in https://github.com/Automattic/socket.io-client/pull/682
