### ISSUE TITLE
doubles connection on reconnect wihout option 'multiplex': false

### ISSUE THREAD

**Issue by meddle1** [Automattic/socket.io#1586]
i create socket in browser with 'reconnection': false option. When i restart server and try to reconnect socket manually with socket.connect() function, it creates two connections, takes all socket events from cache and fires them for both connections.
When i reconnect socket for second time, i get three connections and triple events firing, an so on.
Only option 'multiplex': false prevents creating new connections.

**Comment by rase-** [comment]
Fix merged in #702.
