### ISSUE TITLE
socker.leave BUG!!

### ISSUE THREAD

**Issue by c941010623** [Automattic/socket.io#1629]
when i use socket.leave i will see the => io.sockets.adapter

it's sids and rooms still remain

i think it should be remove

------------------------------------------------
ex; i use socket.leave(roomname)

rooms:
 { '1': { glWpN73i15LcIfgXAAAA: true },
   glWpN73i15LcIfgXAAAA: [ glWpN73i15LcIfgXAAAA: true ],
   MCgNc6Na7BW2I9F_AAAB: [] }, <= still have
sids:
 { glWpN73i15LcIfgXAAAA: { '1': true, glWpN73i15LcIfgXAAAA: true },
   MCgNc6Na7BW2I9F_AAAB: {} },<= still have

when MCgNc6Na7BW2I9F_AAAB is close chrome, it still here ......

should remove when leave

delete io.sockets.adapter.sids[socket.id]
delete io.sockets.adapter.rooms[socket.id]

**Comment by rase-** [comment]
Should be cleaned after a recent-ish patch: https://github.com/Automattic/socket.io-adapter/blob/e66ea47c80539d6b9d9dac636e8edae9075f4486/index.js#L66

**Comment by fabi0w** [comment]
thank you!
