### ISSUE TITLE
你好，Socket.io是不是不支持移动端啊？

### ISSUE THREAD

**Issue by kingzyl** [Automattic/socket.io#1643]
下面的代码是手机端无法弹出提示输入框？？

var socket = io.connect('http://localhost:3000'); 
		var name;
		socket.on('connect', function () {
			name=window.prompt('请设置你的昵称');
		    socket.emit('setname',name);

		    socket.on('message', function(data){
		    	console.log("接受数据"+data);
			  	receives("xiaov",data);
			});
		});

**Comment by rase-** [comment]
I'm not very sure what this issue is about. Does the issue still persist?

**Comment by akakcolin** [comment]
No,I think this issue can be closed.

**Comment by fanweixiao** [comment]
@kingzyl socket.io could use pooling on android webview, you won't need android-websockets.

**Comment by rase-** [comment]
I'll close this, but feel free to reopen if the issue persists.
