### ISSUE TITLE
Timing issue

### ISSUE THREAD

**Issue by fdellabetta** [Automattic/socket.io#1668]
In this example, socket.io-client disconnect while in on 'connect' callback.
By setting different value on setTimeout call (inside io.use middleware)  I get different behaviours.

If that is set to 100, the on 'disconnect' callback (server side) is not called immediately

If that is set to 0 (the same if I call next() without setTimeout) , the on 'disconnect' callback (server side) is called immediately.

If that is set to 2000, the on 'disconnect' callback (server side) is called immediately after 2 seconds

With socket.io version 0.9.16 'disconnect' callback is always called

Could someone explain me why this happens ?
Thanks in advance

Running on ubuntu 14.04 x64 with node 0.10.25 and socket.io 1.0.6.
Server running with node index.js
Client running with browser http://localhost:3456/client

index.js:
```js
	var app=require('express')();
	var fs=require('fs');
	var http=require('http');
	var client=require('socket.io-client');
	
	var server=app.listen(3456);
	var io = require('socket.io').listen(server); 
	
	io.use(function(socket,next){
		setTimeout(next,100);
	})
	
	io.on('connection', function(socket){
		console.log('connected');
		socket.on('disconnect',function(){
			console.log('disconnected');
		});
	});
	
	app.get('/client',function(req,res){
		var socket = client.connect('http://localhost:3456');
		socket.on('connect',function(){
			console.log('socket.io-client connected');
			socket.disconnect();
		});
		socket.on('disconnect',function(){
			console.log('socket.io-client disconnected');
		});
		res.end();
	})
```

**Comment by rase-** [comment]
Already updated.
