### ISSUE TITLE
Namespaced connection events are passed new/different socket objects

### ISSUE THREAD

**Issue by Nick-Riggs** [Automattic/socket.io#1669]
In my case, I'm using middleware to add some custom data to the socket's handshake object. In the non-namespace connection event, I have access to the custom data. However in a connection event for a namespace, there appears to be a completely different socket object.

code to reproduce:

```javascript
var app = require("http").createServer(handler);
var fs = require("fs");

app.listen(80);

function handler (req, res) {
    fs.readFile(__dirname + "/index.html",
        function (err, data) {
            res.writeHead(200);
            res.end(data);
        });
}

var io = require("socket.io")(app);

//some middleware that mods the handshake 
io.use(function(socket, next) {
    socket.handshake.customId = 10;

    next();
});

io.on("connection", function(socket) {
    console.log("customId from / connection event: " + socket.handshake.customId);
});

io.of("/chat").on("connection", function(socket) {
    console.log("customId from /chat connection event: " + socket.handshake.customId);
});
```

```html
<script src="/socket.io/socket.io.js"></script>
<script>
    var io = io.connect("/chat");
</script>
```

Is this expected behavior? If so, where is the correct place to pass data along with a socket object?

**Comment by rase-** [comment]
@Nick-Riggs middleware is namespace specific. When doing `io.use`, it will be default attach the middleware to the default namespace `/`.

You can do `io.of('/chat').use(...)` to attach a middleware to the chat namespace.
