### ISSUE TITLE
Unexpected behavior of room leaving

### ISSUE THREAD

**Issue by GuoZhang** [Automattic/socket.io#1670]
I found that in the released 1.0.6,  leaving a room will result in leaving not only the room but also rooms after it. For example, a user is now in room 'A', 'B' and 'C'. Leaving room 'B' will leave the user in room 'A' only (both 'B' and 'C' disappear). 

By checking the code, lib/socket.js, I found:
```js
Socket.prototype.leave = function(room, fn){
  // ... 
  self.rooms.splice(self.rooms.indexOf(room, 1));
  // ...
  return this;
};
```

I guess there is a missing argument (in order to leave the specific room only).
```js
self.rooms.splice(self.rooms.indexOf(room, 1), 1);
```

**Comment by Hakadel** [comment]
:up: 

I have the same issue, do you have a fix for this bug?
