### ISSUE TITLE
Installing on Windows 8.1 with umlauts in the path

### ISSUE THREAD

**Issue by Zache** [Automattic/socket.io#1676]
I've tried installing socket.io using npm on Windows 8.1 but I get an error which I guess is related to special characters (ö or perhaps space) in the path it tries to install to.

This is what I get when trying npm install -g socket.io using PowerShell running as an admnistrator.

C:\src> npm install -g socket.io
|

> ws@0.4.31 install C:\Users\Zacharias Björngren\AppData\Roaming\npm\node_modules\socket.io\node_modules\engine.io\node_
modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\Zacharias Björngren\AppData\Roaming\npm\node_modules\socket.io\node_modules\engine.io\node_modules\ws>node "C:\
Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Users\Zacharias Björngren\AppData\Roaming\npm\node_modules\socket.io\node_modules\engine.io\node_modules\ws\build\bu
fferutil.vcxproj(44,58): error MSB4025: The project file could not be loaded. Invalid character in the given encoding.
Line 44, position 58.
C:\Users\Zacharias Björngren\AppData\Roaming\npm\node_modules\socket.io\node_modules\engine.io\node_modules\ws\build\va
lidation.vcxproj(44,58): error MSB4025: The project file could not be loaded. Invalid character in the given encoding.
Line 44, position 58.
/

> ws@0.4.31 install C:\Users\Zacharias Björngren\AppData\Roaming\npm\node_modules\socket.io\node_modules\socket.io-clien
t\node_modules\engine.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\Zacharias Björngren\AppData\Roaming\npm\node_modules\socket.io\node_modules\socket.io-client\node_modules\engin
 "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
ne.io-client\node_modules\ws\build\bufferutil.vcxproj(44,58): error MSB4025: The project file could not be loaded. Invai
lid character in the given encoding. Line 44, position 58.
C:\Users\Zacharias Björngren\AppData\Roaming\npm\node_modules\socket.io\node_modules\socket.io-client\node_modules\engi
ne.io-client\node_modules\ws\build\validation.vcxproj(44,58): error MSB4025: The project file could not be loaded. Inva
lid character in the given encoding. Line 44, position 58.
socket.io@1.0.6 C:\Users\Zacharias Björngren\AppData\Roaming\npm\node_modules\socket.io
├── debug@0.7.4
├── has-binary-data@0.1.1 (isarray@0.0.1)
├── socket.io-adapter@0.2.0 (socket.io-parser@2.1.2)
├── socket.io-parser@2.2.0 (isarray@0.0.1, emitter@1.0.1, json3@3.2.6)
├── engine.io@1.3.1 (base64id@0.1.0, debug@0.6.0, engine.io-parser@1.0.6, ws@0.4.31)
└── socket.io-client@1.0.6 (to-array@0.1.3, indexof@0.0.1, component-bind@1.0.0, object-component@0.0.3, component-emitt
er@1.1.2, parseuri@0.0.2, engine.io-client@1.3.1)

**Comment by rauchg** [comment]
Fixed
