### ISSUE TITLE
Failing test connecting to non-default namespace

### ISSUE THREAD

**Issue by fdellabetta** [Automattic/socket.io#1681]
Test is failing with **Error: timeout of 2000ms exceeded**
Ubuntu 14.04 x64, node.js 0.10.29, socket.io 1.0.6

    it('should pass errors when connecting to non-default namespace', function(done){
      var srv = http();
      var sio = io(srv);
      sio.use(function(socket, next){
        next(new Error('Authentication error'))
      });
      srv.listen(function(){
        var socket = client(srv,'/ns');
        socket.on('error', function(err){
          expect(err).to.be('Authentication error');
          done();
        });
      });
    });

**Comment by rase-** [comment]
It seems like there is general agreement for

> Good point… Since now io.on('connection') captures the connections not for all namespaces but for the / namespace, I think .use should only apply to /

Closing.
