### ISSUE TITLE
reconnect not working in v1.0

### ISSUE THREAD

**Issue by KaviSharma** [Automattic/socket.io#1683]
I have this code to connect and disconnect connection-

    var socket = io.connect("/dashbaord", {'forceNew': true});
    socket.on('connect', function (socket) {
        $log.info("new connection established");
    });

    socket.on('disconnect', function (socket) {
        $log.info("connection disconnected");
    });

//socket connection works here

socket.disconnect();  // disconnect event fire here
socket.connect(); // connect event not fire here

//socket connection does not work here

**Comment by rase-** [comment]
Should work after merging https://github.com/Automattic/socket.io-client/issues/732
