### ISSUE TITLE
Can socket.io talk to any clients in the language of websocket?

### ISSUE THREAD

**Issue by ynkm169** [Automattic/socket.io#1689]
Or does socket.io has it's own specific format that sit on top of websocket?
If so, does it mean the only way to talk to socket.io Node server is to implement your own client?

**Comment by rase-** [comment]
There is a protocol implemented on top of WebSockets. See https://github.com/automattic/socket.io-protocol and https://github.com/automattic/engine.io-protocol

There are a lot of great clients for different environments in GitHub, for example a Java client: https://github.com/nkzawa/socket.io-client.java
