### ISSUE TITLE
Volatile emits and rooms

### ISSUE THREAD

**Issue by MyOkram** [Automattic/socket.io#1785]
Hi. I've read everywhere about volatile messages (90% of times it is all about Bierber tweets). My issue is simple. 

    socket.volatile.emit(...)

Seems to work without problem, but these all do not:

    io.to('fooroom').volatile.emit(...)
    Io.volatile.to('fooroom').emit(...)

They all return error (undefined volatile). My question is, how can I send volatile mesaages to all users in a room?

P.S. I've done some tests, and it turns out that if a user gets suddenly disconnected , and then, after hours or so, he connects again, he receives the messages that were sent in that off period, like if Socket.io were savijg them in some sort of buffer. I'm facing serious memory leaks issues, and I think this have something to do.

Thanks.

**Comment by alebedinskiy** [comment]
Hi @rauchg , could you please provide a reason for closing the issue?
I'm also interested in sending volatile messages to a room but it seems there's no API for that.

**Comment by rauchg** [comment]
Closing
