### ISSUE TITLE
Are these docs up to date & minification? 

### ISSUE THREAD

**Issue by JohnMcLear** [Automattic/socket.io#1874]
https://github.com/Automattic/socket.io/wiki/Configuring-Socket.IO

I ask because I was looking at Etherpad optimization and noticed SocketIO file is serving a ~200Kb file.  The solution suggested is to use a CDN but as I mentioned before this is of 0 use to Etherpad.  

I wondered if 

a) The documentation needs updating?
b) There is some movement on minification without a CDN?

PS Etherpad now runs V1+, we still have some issues to resolve but it's holding up okay so far.

**Comment by rase-** [comment]
Closing after @nkzawa's answers.
