### ISSUE TITLE
Critical - Script injection on Chat demo

### ISSUE THREAD

**Issue by cauli** [Automattic/socket.io#1927]
I was poking around the chat demo and found out security breach.
I could inject ```<script>``` tags on every users browsers, and had some sadistic smirk on my face creating alerts for all people.

The thing is: the messages are treated for HTML tags only on the client side, and should also be treated on the server side.

Also, it uses the fact that messages are treated, but usernames are not.

How I did it:

On Chrome inspector:

```javascript
var socket = io('chat.socket.io');
socket.emit('add user', '<script>alert("Breach : (")</script>');
```

But I can imagine it can be used to far worse stuff, like force-visiting other websites, stealing information and such.

**Comment by defunctzombie** [comment]
I tried this and it did not produce an alert dialog.

Also, looking at the code here: https://github.com/Automattic/socket.io/blob/master/examples/chat/public/main.js#L73 it is using the `.text` function which I think sanitizes the text.

Possibly you took additional steps that I did not take to actually cause this to happen?

**Comment by rauchg** [comment]
It used to be a problem, the chat code was out of date on the `chat.socket.io` deployment.
