### ISSUE TITLE
Does socket.io send to everyone or just those that listen?

### ISSUE THREAD

**Issue by ronag** [Automattic/socket.io#1931]
From a performance stand-point. If the server emits messages, e.g. through broadcasting, does it actually send data to all clients or only to those that are listening for the specific message? i.e. is message filtering done locally on remotely?

Would appreciate some clarification and possibly suggest that the documentation clarifies.

**Comment by utan** [comment]
If you do emit or to method the message is sent to those specific channel way to say..

**Comment by ronag** [comment]
Sorry. I didn't understand that. Could you please rephrase?

**Comment by utan** [comment]
If you do in() or to() methods the message will go to that specific channel..

**Comment by peteruithoven** [comment]
The server keeps a record of the clients in namespaces and rooms. It will only send messages to the clients you target from the server (by broadcasting in a namespace or room for example). 
One way to optimize what is send to a client is to separate things in different namespaces. This allows a client to "subscribe to" (connect to) the data he's interested in.  
Maybe you can try to suggest a documentation improvement?

**Comment by rase-** [comment]
What @peteruithoven said. Rooms and namespaces are documented in http://socket.io/docs/rooms-and-namespaces/

Any improvement suggestions are always welcome in https://github.com/Automattic/socket.io-website
