### ISSUE TITLE
Socket.IO not working with wandenberg/nginx-push-stream-module

### ISSUE THREAD

**Issue by g----** [Automattic/socket.io#1933]
Hello, is socket.io compatible with any websocket server or only with its own? 

It seems not to be working with https://github.com/wandenberg/nginx-push-stream-module. 
I tried configuration like this:
```nginx
location ~ ^/socket.io/ {
    push_stream_subscriber               websocket;
    push_stream_channels_path            my_channel;
    push_stream_websocket_allow_publish  off;
    push_stream_allowed_origins          "*";
    push_stream_wildcard_channel_max_qtd 1;
}
```
Does socket.io needs to establish some special kind of handshake or something?
Anyone tried socket.io with that nginx module? 
Any hint how to make it work?

**Comment by nkzawa** [comment]
socket.io has own protocol on top of websocket and http.

https://github.com/automattic/socket.io-protocol

**Comment by g----** [comment]
I see. Thanks for quick reply.

**Comment by g----** [comment]
I see. Thanks for quick reply.
