### ISSUE TITLE
Compression support

### ISSUE THREAD

**Issue by rauchg** [Automattic/socket.io#1947]
- Turned on by default
- For all transports
- Needs benchmarks to understand performance impact
- Depends on merging the excellent engine.io work by @nkzawa  https://github.com/Automattic/engine.io/pull/299

**Comment by rauchg** [comment]
Merged

**Comment by vsdigitall** [comment]
wow nice! my project transfers a lot of plain-text data so this feature was highly awaited

**Comment by klimashkin** [comment]
When could we expect 1.4? Compression is much anticipated feature

**Comment by alex21** [comment]
So what is the current status of this feature?

**Comment by SlvrEagle23** [comment]
We've had a huge demand for this feature with our visitors on limited bandwidth connections, and after researching the progress of this ticket, I decided to hold off on implementing compression "on top of" the socket.io layer.

It seems, though, that while the changes are merged, they're part of a release that has no scheduled date, and has been pending for several months now. Is there any idea when we can reasonably expect this to be shipped?

**Comment by brandonros** [comment]
Did this make it live?

**Comment by andrewmillion** [comment]
Any news?

**Comment by klimashkin** [comment]
@andrewmillion http://socket.io/blog/socket-io-1-4-0/
