### ISSUE TITLE
Latency in `pong` event

### ISSUE THREAD

**Issue by rauchg** [Automattic/socket.io#1951]

**Comment by nanandan** [comment]
@rauchg Hey Guillermo! I'd wanted to work on this milestone and needed to get more info on it. Please let me know what is needed.

**Comment by rauchg** [comment]
Alex is taking a look at it. Maybe you guys can collaborate?

**Comment by nanandan** [comment]
Alright. I will have a chat with him. Thanks.

**Comment by defunctzombie** [comment]
@rauchg What are we trying to measure here? Can you provide a brief description of the problem and what outcome you want from the solution.

**Comment by rauchg** [comment]
Fixed https://github.com/Automattic/socket.io-client/commit/adbd0e3e362eae1d190924c940b03f8687aab954
