### ISSUE TITLE
.join() crashing randomly

### ISSUE THREAD

**Issue by plus-** [Automattic/socket.io#1969]
Hi I'm using
> "socket.io": "~1.2.1",

And I keep getting: 
> TypeError: Cannot call method 'indexOf' of undefined
    at Socket.join (/blablabla/node_modules/socket.io/lib/socket.js:220:19)

I can't pinpoint what's wrong, any hint?

**Comment by ebuildy** [comment]
Looks like:

    if (~this.rooms.indexOf(room)) return this;

rooms is null :/ 

Can you post your code please?

**Comment by plus-** [comment]
There's nothing fancy in the code, it just fails on:

  >  socket.on('join-room', function(roomId) {
    socket.join(roomId);
  });

Appart from that I'm doing some basic API operations like emit/join/leave, I can't see what changes or force the state of the internal rooms to undefined. I can't really reproduce it consistently, it just happens randomly on prod.
