### ISSUE TITLE
1.x pendant to resource

### ISSUE THREAD

**Issue by soliton4** [Automattic/socket.io#1976]
i remember in 0.x it was possible to define something like "resource" to define under what url socket.io is listening.
correct me if i am wrong, it was possible to have several instances of socket.io running, listening on different urls.
is this still possible somehow? i read that 1.x is allways listening under /

**Comment by nkzawa** [comment]
1.x has `path` option instead of `resource`.  And it seems that `resource` also still remains for backward compatibility.
