### ISSUE TITLE
Sending raw binary to a server causes it to crash

### ISSUE THREAD

**Issue by nuclearace** [Automattic/socket.io#1980]
![](https://i.imgur.com/VyIal1F.png)
Causes: `Error: got binary data when not reconstructing a packet`

Caused by: https://github.com/Automattic/socket.io-parser/blob/master/index.js#L252

I would think there would be a gracious way to handle this, rather than crash.

**Comment by rauchg** [comment]
I believe we should be catching this.

**Comment by rauchg** [comment]
PS: nice color scheme

**Comment by rauchg** [comment]
I think we are indeed `try/catch`ing, but we're not handling the error automatically for the user.

**Comment by calzoneman** [comment]
>but we're not handling the error automatically for the user

I wasn't aware there was even a way to manually handle such an error.  I can't seem to find anything in socket.io's documentation related to adding handlers for error events, in any case.

**Comment by rauchg** [comment]
Fixing that.

**Comment by rauchg** [comment]
Fixed in `1.3.3`

**Comment by fredx21** [comment]
I am using socket.io 1.3.5 and I have this problem hitting me very bad, it can even crashed my nodejs server (ouch). I do use binary to transmit my messages. Sometimes it works fines, sometimes I get that error. Curiously, I only get this error on my linux AWS station running nodejs v0.10.33. On my Windows 7 x64 with nodejs v0.10.38, I never get this error. I can replicate the error somewhat easily by restarting my nodejs (from an SSH console) on AWS and letting the clients reconnect automatically, generating this error about 1 time out of 10 tries.

My clients are using the latest SocketIoClientDotNet (https://github.com/Quobject/SocketIoClientDotNet), a C# port of socket-io-client that is use in my Android and iOS clients.

Does anyone have an idea about what is causing this situation? Can the clients mis-behave and provoke that server behavior?

**Comment by nkzawa** [comment]
@fredx21 It sounds like the issue of SocketIoClientDotNet. Can you reproduce the problem with node.js client?

**Comment by fredx21** [comment]
Thank you nkzawa, more testing is needed to definetly conclude, but it preliminarily seems like you were right on and its a problem with my usage interpretation of SocketIoClientDotNet.

**Comment by calzoneman** [comment]
It doesn't matter if the bug is only triggered by a custom client, it's still a problem with the socket.io server if a client can send maliciously crafted data to crash the server.

**Comment by rauchg** [comment]
I believe there wasn't a crash, just an `error` here?

**Comment by calzoneman** [comment]
You're right, I was misunderstanding the original comment in the context of the title of the issue.

**Comment by ShavidzeT** [comment]
@nuclearace please update image url.
