### ISSUE TITLE
session id unknown

### ISSUE THREAD

**Issue by japrescott** [Automattic/socket.io#1982]
I've noticed strange behavior connecting from my android phone (4.3.3, stockbrowser) that I haven't seen happening in my desktop browser. This happens 50% of the time;
first request (without sid) gets back the sid "ABC" and on the server I see my authentication fn called and everything is good. The next 1-3 requests use the sid "ABC" and everything goes (200) until I suddenly get a 400, "session id unknown". After that it gets a new sid"DEF" (like in the first request) and it works for 2-3 requests.
This happens about 4 times until a sid is in place, which doesn't trigger a "session id unknown" anymore.
And as stated in the beginning, the whole "session id unknown" happens only on mobile and only 50% of the time.

My app is running clustered (multicore) but I am using a redis session store for the authentification (both in express and socket). Could it be that socket.io somehow has a special additional function for authenticating the 'sid'? Or is there a parameter to pass my redis-session-store?

Thanks for any kind of help

**Comment by japrescott** [comment]
so I looked at the doc again and I saw an "adapter" that I have never seen before (I assumed this was handled by the authentication method but could have changed since 0.9).
Sadly, this doesn't fix the "session id unknowns" as I hoped for. Is there any other part of socket.io that does something with the 'sid'?

**Comment by japrescott** [comment]
some more infos: Polling is the problem, via websocket it always works and sid is never bad! Chrome on android supports websockets, while the stock browser (and thus the webview -> cordova) doesn't. So chrome always works, while the stock-browser tries websocket but as it isn't supported falls back to polling where the "session id unknown" is thrown.

The problem that I have from this is that I first get a "connect" event, emit a msg and while emitting, a 400 "session id unknown" is returned, causing a "error" and a "disconnect" and then dropping my emitted msg. So my client is left in a state of unknowing if the msg went through or not.

**Comment by rase-** [comment]
@japrescott are you doing sticky load balancing? The polling transport needs consequent requests to hit the same socket.io process. The problem doesn't exist if using WebSockets only, which might explain this behaviour.

**Comment by japrescott** [comment]
@rase- thank you for your answer. No, I am not using sticky load balancing as (outlined here)[http://socket.io/docs/using-multiple-nodes/]. I assumed that by using redis for authetification and using redis as an adapter would solve this issue.
As I understand you, I also need sticky sessions within nginx AND sticky sessions within the node cluster for this to scale multiple processes? So 4 things?

**Comment by rase-** [comment]
@japrescott: Any form of load balancing should be enough, so either in the node cluster level or nginx level.

**Comment by peteruithoven** [comment]
To correct @rase-, when load balancing, it needs to be done sticky. Please see: 
http://socket.io/docs/using-multiple-nodes/#

**Comment by rase-** [comment]
Aye, I did mean any form of _sticky_ load balancing. Thanks for clearing that up @peteruithoven

**Comment by japrescott** [comment]
thank you @rase- and @peteruithoven! using 'ip_hash' for nginx and the sticky-sessions module (while rewriting parts of it) gave me the solution that fixxed the "session id unknown" and now everything (at least seems) to be working :)
Thank you very much for your time and your valuable input! Very much appreciated!

**Comment by japrescott** [comment]
one last question -> I saw discussions about pm2 supporting sticky sessions so it would work with socket.io but the devs seemed to push it back as a "socket.io problem". Do you know if this is a priority to fix and if there are talks taking place between socket.io and pm2?

**Comment by OGFaisalN** [comment]
> To correct @rase-, when load balancing, it needs to be done sticky. Please see: http://socket.io/docs/using-multiple-nodes/#

The updated link is: https://socket.io/docs/v4/using-multiple-nodes/#sticky-load-balancing
