### ISSUE TITLE
'watch' and 'unwatch' as event names crash socket.io on Firefox

### ISSUE THREAD

**Issue by Canop** [Automattic/socket.io#1983]
You get the bug with : 
    
    socket.on('unwatch', function(...

Why Firefox ? Probably because the new `Object.prototype.watch()` and `Object.prototype.unwatch()` are only implemented on Firefox.

A call to  `hasOwnProperty` might be missing somewhere.

**Comment by nkzawa** [comment]
This seems the problem of `component-emitter`. It keeps event listeners in an object, but `watch` and `unwatch` are methods actually, so this error happens.

https://github.com/component/emitter/blob/master/index.js#L45

```
TypeError: undefined is not a function {stack: (...), message: "undefined is not a function"}
```

The same problem occurs on other browsers too when you use another reserved key like `constructor`.

```js
socket.on('constructor', function() {});
```

**Comment by rauchg** [comment]
Great find
