### ISSUE TITLE
Characters 8220 & 8221 are replaced with 28 (FS) & 29 (GS) when emitting/receiving a message

### ISSUE THREAD

**Issue by ismriv** [Automattic/socket.io#1987]
To reproduce, I emit a message such as “test” which contains characters 8220 & 8221. I've checked down to engine.io, and the packet seems to have the quote characters.

However, when received by the client, these characters seem to have been replaced with FS & GS. I've verified this in the Websockets tab under Network in Chrome as well:

```
engine.io-client:socket socket receive: type "message", data ... <FS>test<GS> // added just for illustration purposes
```

The log statement `socket.io-parser decoded` followed by `engine.io-client:socket socket receive` is missing in this case, and therefore the function added to `on` does not fire.

Any ideas?

**Comment by nkzawa** [comment]
Thank you for reporting the issue. Could you post the actual code you tried?

**Comment by ismriv** [comment]
Sorry for taking so long to get back to you.

We must have been using an old version of socket.io-client, after upgrading to 1.3.5 the issue is solved. It could have been related to https://github.com/Automattic/socket.io/issues/2018
