### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded (on object)

### ISSUE THREAD

**Issue by Bombe93** [Automattic/socket.io#1989]
Normal data pass working but with object not working.

Server:

 socket.on('destroyObjetSphere', function (object) {
        //ob1 = object;  
        //socket.broadcast.emit('destroyObjetSphere', ob1);
});

Client:

   fire : function(pickInfo) {
         if (this.canFire) {
             if (pickInfo.hit && pickInfo.pickedMesh.name === "target") {
                
                pickInfo.pickedMesh.explode(); 
                
                socket.emit('destroyObjetSphere', pickInfo.pickedMesh); 
                

Gives me this error "Uncaught RangeError: Maximum call stack size exceeded" in the file socket.io line 5403(in this funcion):

 for (var key in obj) {
        if (Object.prototype.hasOwnProperty.call(obj, key) && _hasBinary(obj[key])) {
          return true;
        }
      }

is there a problem to pass object? (normal variables work)

**Comment by nkzawa** [comment]
I'd like to know the value of `pickInfo.pickedMesh`. Does it have a circular reference?

**Comment by Bombe93** [comment]
Yes,

i resolved as well:

server side: var objectname = pickInfo.pickedMesh.name; 

client side: var test = scene.getMeshByName(pickInfopickedMesh);

**Comment by melcarniel** [comment]
I got the same issue, how can I emit the object with circular reference?

req.query(`SELECT
      v.cd_emp as codigoEmpresa,
      RTRIM(LTRIM(v.cd_vend)) as codigoVendedor,
      LTRIM(RTRIM(v.cd_equipe)) as codigoEquipe,
      RTRIM(LTRIM(v.cd_vend)) + ' - ' + v.nome as nome,
      v.end_res as endereco,
      v.bairro_res as bairro,
      v.munic_res as municipio,
      v.est_res as estado,
      v.cep_res as cep,
      latitude,
      longitude
  FROM
      vendedor v
      INNER JOIN equipe e ON v.cd_equipe = e.cd_equipe AND v.cd_emp = e.cd_emp
      INNER JOIN gerencia g ON e.cd_gerencia = g.cd_gerencia AND e.cd_emp = g.cd_emp
  WHERE
      v.ativo = 1 AND	
      v.cd_vend NOT LIKE 'VERBAE%' 
  ORDER BY
      cd_vend`, 
      function(err, array){
         
        if(err)
        {
          console.log("err db");
        }
        else{
          let resultado = array.recordset

         
          var ciphertext = crypto.AES.encrypt(JSON.stringify(resultado), 'secret key 123');
          
          io.emit("Data-from-server", ciphertext);

**Comment by shubh0123** [comment]
> Yes,
> 
> i resolved as well:
> 
> server side: var objectname = pickInfo.pickedMesh.name;
> 
> client side: var test = scene.getMeshByName(pickInfopickedMesh);

how you resolved this Issue?
