### ISSUE TITLE
{ [Error: xhr post error] type: 'TransportError', description: 503 }

### ISSUE THREAD

**Issue by lonso** [Automattic/socket.io#1995]
socket.io client connect server 
client throw this error
```javascript
{ [Error: xhr post error] type: 'TransportError', description: 503 }
```

more error info

```javascript
  socket.io-client:manager will wait 1167ms before reconnect attempt +0ms
  engine.io-client:socket probe transport "websocket" failed because of error: socket closed +1ms
  engine.io-client:socket socket error {"description":503} +0ms
  socket.io-client:manager error +1ms { [Error: xhr poll error] description: 503 }

```

other question
why i use socket.io-client connect server ,the transport is polling not websocket?

**Comment by nkzawa** [comment]
What versions of server and client do you use? You basically need to use a same version.

> why i use socket.io-client connect server, the transport is polling not websocket?

This is because socket.io uses polling first and attempt to upgrade transport to websocket by the default setting.

**Comment by lonso** [comment]
i used socket.io and socket.io-client v.1.3.3

**Comment by nkzawa** [comment]
Umm, I believe this is not the problem of socket.io since it sounds a very basic error and is well tested.
Could you check your code again? Please post your code here If you couldn't resolve this.

**Comment by lonso** [comment]
i used socket.io-client to stress test.
server code:
```javascript
//app is express V.3.x
var server = exports.server = require('http').createServer(app);
var io = exports.io = require('socket.io')(server, {
	allowUpgrades: true,
	transports: ['websocket', 'flashsocket', 'polling'],
	'log level': 1,
	'pingTimeout': 1000 * 80, 
	'pingInterval': 1000 * 25
});
var RedisStore = require('socket.io-redis');
var pub = redis.createClient(config.redis.port, config.redis.ip);
var sub = redis.createClient(config.redis.port, config.redis.ip, {detect_buffers: true});
io.adapter(RedisStore({pubClient: pub, subClient: sub}));
```
client code:
```javascript
io.connect(config.serverAdd + '/wsservices', {
			'forceNew': true,
			'sync disconnect on unload': true,
			reconnect: false,
			query: {
				bestvid: "___" + bestId + "___",
				client_id: clientId,
				client_name: bestId,
				token: token,
				platform: platform
			}
		});
```

**Comment by nkzawa** [comment]
So it seems your app was upgraded from 0.9.x to 1.3.3. I think you have to fix some options for the latest version, since there are a ton of changes between these versions.
Especially, I wonder the `transports` would work with the setting (`['websocket', 'flashsocket', 'polling']`).

**Comment by lonso** [comment]
client or server?

**Comment by nkzawa** [comment]
Both have to be fixed.  Please see the doc for the details. 

http://socket.io/docs/migrating-from-0-9

**Comment by lonso** [comment]
i write a testcase to stress test.
i run 1000 client to connect server once.
when i run three time's the connect will be slowly and many reconnect event.
```javascript
[root@localhost]# ulimit 
unlimited
```
i don't know why, in the v0.9 not existed this question.

**Comment by lonso** [comment]
fixed,this error need to set client transports like this.
```javascript
io.connect(config.serverAdd + '/wsservices', {
			...
			transports: ['websocket''],
			....
		});
```

**Comment by minhquankq** [comment]
When I set `transports` to `['websocket']`, I got an error `'connect_error', [Error: websocket error]`. But, when I change to `{ transports: ['websocket'] }`, I also got an error ` 'connect_error', [Error: xhr poll error]`

**Comment by crisppY** [comment]
+1

**Comment by dulin666** [comment]
+1

**Comment by ningacoding** [comment]
@minhquankq how did you solve it?

**Comment by lokk3d** [comment]
+1 here (after many connection depending on the hardware machine)
