### ISSUE TITLE
Setting options is not working

### ISSUE THREAD

**Issue by bekite** [Automattic/socket.io#2010]
I want to change the ping timeout using the following code:
```
var io = require('socket.io', {
  pingTimeout: 30000
}).listen(3000)
```
Running the app with ```DEBUG=* node app.js```, I can see that the ping timeout is not updated. It remains at its default value of 60000.
I have socket.io version 1.3.4 installed.

**Comment by Nibbler999** [comment]
You are passing the options to require instead of to socket.io

```javascript
var io = require('socket.io')({
  pingTimeout: 30000
}).listen(3000);
```

**Comment by bekite** [comment]
@Nibbler999 Sorry this was a typo. I didn't copy & paste the code. The code you posted is what I have and that's not working. I found the solution by further investigating the docs.

You need to provide the options object to the listen function:
```
var io = require('socket.io').listen(3000, {
  pingTimeout: 30000
})
```
