### ISSUE TITLE
Socket.io debug tool

### ISSUE THREAD

**Issue by peteruithoven** [Automattic/socket.io#2014]
I'm not sure how else to share this, so I'm sharing it here. 
I've created a *socket.io debug client* that allows you to, sort of chat with a regular Socket.io server. 
It's created to easily play with / debug a Socket.io based API. 

Features: 
1. It let's you connect to a socket.io server,
2. optionally a specific namespace,
3. receive all events,
4. send events,
5. receive responses,
6. though a simple chat interface.

It currently uses [yaml](https://en.wikipedia.org/wiki/YAML) to make json easier to read and write. 

Code, MIT licensed, at: https://github.com/Doodle3D/socket.io-debug-client/
Demo version, that can connect to any server, is available at: http://www.doodle3d.com/debug/

![screenshot](https://cloud.githubusercontent.com/assets/523210/6284360/80f9cc84-b8ef-11e4-82a7-5c260647396b.png)

![screenshot-responsive](https://cloud.githubusercontent.com/assets/523210/6284361/82b848ca-b8ef-11e4-8dd1-1e7eb5d81e59.png)

![screenshot-errors](https://cloud.githubusercontent.com/assets/523210/6284362/83e45d06-b8ef-11e4-970d-c117dbbcbc26.png)

**Comment by asyncanup** [comment]
So what are you suggesting?
I don't see this as having much to do with the core socket.io library.

You can publish the package to npm, and promote it for use by application developers.

Can we close the issue?

**Comment by peteruithoven** [comment]
It's not a suggestion, but I didn't really see another channel to share this on. Seeing there are very few dev tools for socket.io I was hoping it would be useful for others.

**Comment by PedroDank** [comment]
Thanks a lot, peteruithoven, for this! Its been great to test some of my CORS settings and Authorization :+1:
