### ISSUE TITLE
Set a Websocket using nodeJs and Pm2

### ISSUE THREAD

**Issue by cybermarkus1** [Automattic/socket.io#2019]
im not able to properly connect websockets on my nodeJs App. (Unexpected response code: 502)

````
WebSocket connection to 'ws://ayxos.com/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 502
````

My node app.js SERVER config file:

````
var io = require('socket.io')(http)
...
// Set up Socket.IO to listen on port 9000
socket = io.listen(9000);

````

My node CLIENT app.js file:
````

        host            = 'myDomain/socket.io/',
...
        // Initialise socket connection
        socket = io.connect(host, {port: PORT, transports: ["websocket"]});
````

My Nginx Conf:

````
    #proxy to a node app running on 8006 port
    location /zombi/ {
    	proxy_set_header Upgrade $http_upgrade;
    	proxy_set_header Connection "upgrade";
    	proxy_http_version 1.1;
    	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    	proxy_set_header Host $host;
	proxy_pass http://localhost:8006/;
    }
...
    location /socket.io/ {
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_http_version 1.1;
        proxy_pass http://localhost:9000/;
    }
````
What am i doing wrong?

Thanks

**Comment by peteruithoven** [comment]
Are you sure Nginx forwards 8006 to 9001?

**Comment by cybermarkus1** [comment]
i dont know how to do that, i mean, "zombi" is already listening 8006 port, Do i have to create another location to listening 9001 websocket port?

**Comment by cybermarkus1** [comment]
got it:
http://nginx.com/blog/websocket-nginx/

**Comment by cybermarkus1** [comment]
Yes, im doing that but still i have the 503 error i dont know why.

**Comment by cybermarkus1** [comment]
done. i was using io.connect(host) instead of io()

**Comment by jiger25783** [comment]
Looks like PM2 do not support websocket (or any thing other than stateless) in cluster mode if you are running in cluster mode.

**Comment by jiger25783** [comment]
http://pm2.keymetrics.io/docs/usage/cluster-mode/#statelessify-your-application
