### ISSUE TITLE
"Old options" transport:ws required to get redis/cluster working

### ISSUE THREAD

**Issue by jordanpappas** [Automattic/socket.io#2023]
It seems as though socket.io 1.x.x doesn't use the options object or that it is only there for "backwards compatability". I have cluster/redis/socket.io working. The last step was a bit difficult to fix. Socket.io-client for node/browser does not work when "polling" is set as the first (or only) "transport" option. The server and clients must have "transports": ['websocket'] set as the first/only option. I know these options cascade down into the engine.io socket object. Why does cluster/redis not support polling? Can this issue be fixed, removing the need to explicitly set the option to websocket? Is there a time when websockets would fail and polling would be needed, and am I losing this functionality? Thanks.

**Comment by nkzawa** [comment]
Do you have multiple socket.io servers on your environment? It sounds you need sticky session.

http://socket.io/docs/using-multiple-nodes/

**Comment by gui-surfcrew** [comment]
Seems like sticky-session gem is not being maintained. There isn't a code change in 2 years. Any other options?
