### ISSUE TITLE
fetch failed error while installing in Ubuntu using npm

### ISSUE THREAD

**Issue by arunvelsriram** [Automattic/socket.io#2024]
When I try to install using npm I get the following error and am sure I have an active network connection. The github link works when accessed from the browser.

npm ERR! fetch failed https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
 
\> ws@0.5.0 install /home/arun/GitProjects/selfie-showcase/node_modules/socket.io/node_modules/engine.io/node_modules/ws
\> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory \`/home/arun/GitProjects/selfie-showcase/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory \`/home/arun/GitProjects/selfie-showcase/node_modules/socket.io/node_modules/engine.io/node_modules/ws/build'
npm ERR! fetch failed https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
npm ERR! fetch failed https://github.com/rase-/node-XMLHttpRequest/archive/a6b6f2.tar.gz
npm ERR! network tunneling socket could not be established, cause=getaddrinfo ENOTFOUND
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-proxy"
npm ERR! cwd /home/arun/GitProjects/selfie-showcase
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ECONNRESET
npm ERR! not ok code 0

**Comment by arunvelsriram** [comment]
Worked after deleting proxy settings (including https) from th npm config file.

`npm config delete proxy`
`npm config delete https-proxy`

**Comment by feresr** [comment]
Sorry guys, this is still happening to me. I'm no able to download that specific package, how come I can download it a simple "node install xmlhttprequest@1.5.0" but I npm doesn't seem to be able to do so when I do "npm install socket.io@1.3.5"
