### ISSUE TITLE
multiple copy connections

### ISSUE THREAD

**Issue by alex-rokabilis** [Automattic/socket.io#2039]
I tried a simple example such as:
Client connects,
Server send a list of all socket ids currently connected, to all sockets.
If you make fast refreshes on browser, at sometime the server loses some disconnects and send as currently connected sockets, sockets that were disconnected. There is only one client hitting refresh but it will return 2 or more (after time) sockets as connected. It sounds like socketio leaves zombie connections in memory, this thing stops after 45-60 seconds or with server restart.

Server code:
   `io.on('connection', function(socket){
    io.sockets.emit('server_status',io.sockets.sockets.map(function(x){return x.id;}))
    });
`
Browser code:
`socket.on('server_status',function(data){
  console.log(data);
})`

Is this a known bug? Or am I making something wrong?

**Comment by nkzawa** [comment]
I think this is not a bug. The server waits ping timeout to detect unexpected disconnection, so in this case it looks the connection remained for a while.
