### ISSUE TITLE
Is it possible to use socket.io across multiple nodes without sticky sessions?

### ISSUE THREAD

**Issue by cappslock** [Automattic/socket.io#2066]
I'm trying to use socket.io in a setup which makes use of the node.js cluster module and also has multiple processes behind a load balancer. Based on reading [this section of the docs](http://socket.io/docs/using-multiple-nodes/) I see that I need to set up sticky sessions pretty much throughout my stack. For reasons that I don't want to get into this is difficult to do.

Is it possible to use socket.io across multiple nodes without sticky sessions? Ideally I'd like to use a redis store, but the socket.io-redis module doesn't seem to work at all for this use case.

**Comment by cappslock** [comment]
Found this issue: https://github.com/Automattic/socket.io/issues/1853

Short answer is "no" then? Is using `transports: ['websocket']` supposed to work? I wasn't able to get it to with cluster enabled.

**Comment by peteruithoven** [comment]
The socket.io-redis module doesn't solve the need for sticky sessions, it does solve other issues. 
I would advice against using the cluster module, start a couple of instances on different ports (with something like pm2) and do the load balancing in your proxy (like HAProxy). 

I'm not 100% sure, but I think sticky sessions are needed for the long polling. So maybe you can experiment by making your clients only connect over the websocket transport.

**Comment by rauchg** [comment]
Just like @peteruithoven said

**Comment by BruceHem** [comment]
Well after 2 years, what would u guys suggest me to do? Having similar problems. 

Does running instances in different ports differ from running the instance in cluster?

**Comment by darrachequesne** [comment]
@BruceHem sticky-session is still required if the `polling` transport is enabled. That can be achieved either with ip hashing or with a cookie ([example](https://github.com/socketio/socket.io/tree/master/examples/cluster-haproxy)).
