### ISSUE TITLE
Socket.io client ignoring port when namespace used

### ISSUE THREAD

**Issue by codan84** [Automattic/socket.io#2067]
I have described the issue in this stackoverflow post:
http://stackoverflow.com/questions/29290563/socket-io-client-ignoring-port-when-namespace-used-bug

Seems like in the file socket.io.js on line 1050 'loc.host' should be used instead of 'loc.hostname'. This stops port auto-detection from working if connecting client to a namespace:

    var admin_socket = io('/admin');

The port is omitted in this case and CORS errors thrown when attempting to connect.  
I have edited my local copy of this file to use loc.host and port is included in request url again.

**Comment by MrOrz** [comment]
@codan84 closed the issue because it's a dup of https://github.com/Automattic/socket.io-client/issues/812.
Just leaving a trace for those who also bumped into this question :)
