### ISSUE TITLE
Can add a socket to a room multiple times

### ISSUE THREAD

**Issue by jwalton** [Automattic/socket.io#2071]
The problem is here:

https://github.com/Automattic/socket.io/blob/master/lib/socket.js#L218-L229

If you write something like:

    socket.join 'awesome'
    socket.join 'awesome'

the first call to `join()` will end up calling into `adapter.add(...)`, and won't push 'awesome' onto `self.rooms` until the adapter.add callback runs.  Since the [adapter](https://github.com/Automattic/socket.io-adapter/blob/master/index.js#L70) runs the callback on the next tick, this means the second call to `join()` will pass [this check](https://github.com/Automattic/socket.io/blob/master/lib/socket.js#L221) and we'll end up adding the room twice.

**Comment by rauchg** [comment]
The call to add to `rooms` should be idempotent. We're addressing this by turning `rooms` into an ES6 `Set`.
