### ISSUE TITLE
Socket.io with npm on windows 8.1

### ISSUE THREAD

**Issue by quisse** [Automattic/socket.io#2072]
I wan't to install socket.io with npm 2.7.4, node 0.12.2 on windows 8.1 & get this error:

modules\engine.io-client\node_modules\ws\build\validation.vcxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(518): error C4430: missing type specifier - in t assumed. Note: C++ does not support default-int [C:\Users\Tommy\Documents\MEG A\schooljaar4sem2\WebAndMobile\websocket\node_modules\socket.io\node_modules\so cket.io-client\node_modules\engine.io-client\node_modules\ws\build\validation.v cxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(490): error C2065: 'request' : undeclared iden tifier [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\no de_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-clien t\node_modules\ws\build\validation.vcxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(490): error C2228: left of '.data' must have c lass/struct/union [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\w ebsocket\node_modules\socket.io\node_modules\socket.io-client\node_modules\engi ne.io-client\node_modules\ws\build\validation.vcxproj] type is ''unknown-type'' C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(529): error C2039: 'NewSymbol' : is not a memb er of 'v8::String' [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\ websocket\node_modules\socket.io\node_modules\socket.io-client\node_modules\eng ine.io-client\node_modules\ws\build\validation.vcxproj] C:\Users\Tommy.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : see decl aration of 'v8::String' C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(529): error C3861: 'NewSymbol': identifier not found [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\no de_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-clien t\node_modules\ws\build\validation.vcxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(536): error C2039: 'NewSymbol' : is not a memb er of 'v8::String' [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\ websocket\node_modules\socket.io\node_modules\socket.io-client\node_modules\eng ine.io-client\node_modules\ws\build\validation.vcxproj] C:\Users\Tommy.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : see decl aration of 'v8::String' C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(536): error C2228: left of '.As' must have cla ss/struct/union [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\web socket\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine .io-client\node_modules\ws\build\validation.vcxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(536): error C2059: syntax error : ')' [C:\User s\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modules\sock et.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ ws\build\validation.vcxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(549): error C2039: 'New' : is not a member of 'v8::String' [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websoc ket\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io -client\node_modules\ws\build\validation.vcxproj] C:\Users\Tommy.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : see decl aration of 'v8::String' C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(550): error C2466: cannot allocate an array of constant size 0 [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\we bsocket\node_modules\socket.io\node_modules\socket.io-client\node_modules\engin e.io-client\node_modules\ws\build\validation.vcxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(550): error C2440: 'initializing' : cannot con vert from 'int' to 'v8::Local' [C:\Users\Tommy\Documents\MEGA\schooljaar4sem 2\WebAndMobile\websocket\node_modules\socket.io\node_modules\socket.io-client\n ode_modules\engine.io-client\node_modules\ws\build\validation.vcxproj] with [ T=v8::Value ] No constructor could take the source type, or constructor overload re solution was ambiguous C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(549): error C3861: 'New': identifier not found [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_mod ules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node _modules\ws\build\validation.vcxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(555): error C2065: 'uv_work_t' : undeclared id entifier [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\ node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-cli ent\node_modules\ws\build\validation.vcxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(555): error C2065: 'req' : undeclared identifi er [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_m odules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\no de_modules\ws\build\validation.vcxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(555): error C2448: 'NanAsyncExecute' : functio n-style initializer appears to be a function definition [C:\Users\Tommy\Documen ts\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modules\socket.io\node_modu les\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\valida tion.vcxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(560): error C2065: 'uv_work_t' : undeclared id entifier [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\ node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-cli ent\node_modules\ws\build\validation.vcxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(560): error C2065: 'req' : undeclared identifi er [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_m odules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\no de_modules\ws\build\validation.vcxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(560): error C2448: 'NanAsyncExecuteComplete' : function-style initializer appears to be a function definition [C:\Users\Tommy \Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modules\socket.io\n ode_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\buil d\validation.vcxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(570): error C2039: 'request' : is not a member of 'NanAsyncWorker' [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobil e\websocket\node_modules\socket.io\node_modules\socket.io-client\node_modules\e ngine.io-client\node_modules\ws\build\validation.vcxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\ node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-c lient\node_modules\ws\node_modules\nan\nan.h(487) : see declaration of 'NanAs yncWorker' C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(571): error C2065: 'NanAsyncExecute' : undecla red identifier [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\webs ocket\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine. io-client\node_modules\ws\build\validation.vcxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(571): error C2065: 'uv_after_work_cb' : undecl ared identifier [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\web socket\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine .io-client\node_modules\ws\build\validation.vcxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(572): error C2146: syntax error : missing ')' before identifier 'NanAsyncExecuteComplete' [C:\Users\Tommy\Documents\MEGA\scho oljaar4sem2\WebAndMobile\websocket\node_modules\socket.io\node_modules\socket.i o-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj ] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(572): error C2059: syntax error : ')' [C:\User s\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modules\sock et.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ ws\build\validation.vcxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(716): error C2661: 'v8::Local::New' : no ov erloaded function takes 1 arguments [C:\Users\Tommy\Documents\MEGA\schooljaar4s em2\WebAndMobile\websocket\node_modules\socket.io\node_modules\socket.io-client \node_modules\engine.io-client\node_modules\ws\build\validation.vcxproj] with [ T=v8::String ] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(769): error C2039: 'AsciiValue' : is not a mem ber of 'v8::String' [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile \websocket\node_modules\socket.io\node_modules\socket.io-client\node_modules\en gine.io-client\node_modules\ws\build\validation.vcxproj] C:\Users\Tommy.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : see decl aration of 'v8::String' C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(769): error C2065: 'AsciiValue' : undeclared i dentifier [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket \node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-cl ient\node_modules\ws\build\validation.vcxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(769): error C2146: syntax error : missing ';' before identifier 'value' [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAnd Mobile\websocket\node_modules\socket.io\node_modules\socket.io-client\node_modu les\engine.io-client\node_modules\ws\build\validation.vcxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(769): error C3861: 'value': identifier not fou nd [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_m odules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\no de_modules\ws\build\validation.vcxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(817): warning C4267: 'argument' : conversion f rom 'size_t' to 'int', possible loss of data [C:\Users\Tommy\Documents\MEGA\sch ooljaar4sem2\WebAndMobile\websocket\node_modules\socket.io\node_modules\socket. io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxpro j] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(829): warning C4267: 'argument' : conversion f rom 'size_t' to 'int', possible loss of data [C:\Users\Tommy\Documents\MEGA\sch ooljaar4sem2\WebAndMobile\websocket\node_modules\socket.io\node_modules\socket. io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxpro j] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(832): error C2065: 'value' : undeclared identi fier [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node _modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\ node_modules\ws\build\validation.vcxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(840): error C2065: 'value' : undeclared identi fier [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node _modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\ node_modules\ws\build\validation.vcxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(840): error C2228: left of '.length' must have class/struct/union [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile \websocket\node_modules\socket.io\node_modules\socket.io-client\node_modules\en gine.io-client\node_modules\ws\build\validation.vcxproj] type is ''unknown-type'' C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(858): warning C4267: 'argument' : conversion f rom 'size_t' to 'int', possible loss of data [C:\Users\Tommy\Documents\MEGA\sch ooljaar4sem2\WebAndMobile\websocket\node_modules\socket.io\node_modules\socket. io-client\node_modules\engine.io-client\node_modules\ws\build\validation.vcxpro j] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(873): error C2065: 'value' : undeclared identi fier [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node _modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\ node_modules\ws\build\validation.vcxproj] C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modul es\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_m odules\ws\node_modules\nan\nan.h(873): error C2228: left of '.length' must have class/struct/union [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile \websocket\node_modules\socket.io\node_modules\socket.io-client\node_modules\en gine.io-client\node_modules\ws\build\validation.vcxproj] type is ''unknown-type'' ..\src\validation.cc(108): error C2248: 'v8::HandleScope::HandleScope' : cannot access protected member declared in class 'v8::HandleScope' [C:\Users\Tommy\Do cuments\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modules\socket.io\node _modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\build\v alidation.vcxproj] C:\Users\Tommy.node-gyp\0.12.0\deps\v8\include\v8.h(816) : see decla ration of 'v8::HandleScope::HandleScope' C:\Users\Tommy.node-gyp\0.12.0\deps\v8\include\v8.h(800) : see decla ration of 'v8::HandleScope' ..\src\validation.cc(109): error C2664: 'v8::FunctionTemplate::New' : cannot co nvert parameter 1 from 'void (__cdecl *)(const v8::FunctionCallbackInfo &)' to 'v8::Isolate *' [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\ websocket\node_modules\socket.io\node_modules\socket.io-client\node_modules\eng ine.io-client\node_modules\ws\build\validation.vcxproj] with [ T=v8::Value ] There is no context in which this conversion is possible ..\src\validation.cc(112): error C2039: 'NewSymbol' : is not a member of 'v8::S tring' [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\no de_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-clien t\node_modules\ws\build\validation.vcxproj] C:\Users\Tommy.node-gyp\0.12.0\deps\v8\include\v8.h(1599) : see decl aration of 'v8::String' ..\src\validation.cc(112): error C3861: 'NewSymbol': identifier not found [C:\U sers\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\node_modules\s ocket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modul es\ws\build\validation.vcxproj] ..\src\validation.cc(134): error C2660: 'v8::True' : function does not take 0 a rguments [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket\ node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-cli ent\node_modules\ws\build\validation.vcxproj] ..\src\validation.cc(134): error C2660: 'v8::False' : function does not take 0 arguments [C:\Users\Tommy\Documents\MEGA\schooljaar4sem2\WebAndMobile\websocket \node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-cl ient\node_modules\ws\build\validation.vcxproj] socket.io@1.3.5 node_modules\socket.io ├── debug@2.1.0 (ms@0.6.2) ├── has-binary-data@0.1.3 (isarray@0.0.1) ├── socket.io-adapter@0.3.1 (object-keys@1.0.1, debug@1.0.2, socket.io-parser@2. 2.2) ├── socket.io-parser@2.2.4 (isarray@0.0.1, debug@0.7.4, component-emitter@1.1.2, benchmark@1.0.0, json3@3.2.6) ├── engine.io@1.5.1 (base64id@0.1.0, debug@1.0.3, engine.io-parser@1.2.1, ws@0.5 .0) └── socket.io-client@1.3.5 (to-array@0.1.3, indexof@0.0.1, component-bind@1.0.0, debug@0.7.4, backo2@1.0.2, object-component@0.0.3, component-emitter@1.1.2, has -binary@0.1.6, parseuri@0.0.2, engine.io-client@1.5.1)

**Comment by quisse** [comment]
I have visual studio 2012 express for compiling

**Comment by aaandrew** [comment]
Check this link out:
https://github.com/Automattic/socket.io/issues/2057

**Comment by quisse** [comment]
that dirty way fixed it for now, thanks!

**Comment by albhardy** [comment]
I managed to install using `npm install socket.io --msvs-version=2013`
