### ISSUE TITLE
Socket.io client for lua

### ISSUE THREAD

**Issue by mohaalak** [Automattic/socket.io#2073]
Hi 
I have a problem it's not an issue . but I don't know where to start. 
we created a web game application using sails.js and socket.io now we want to build an android and ios game for it. we want to use a game enigne that use lua for scripting. 
can you give me a hint where should I start to implement client system for lua , I even can use c++ implementation of socket.io client to develop the game engine.
do you have any idea where should I be looking?

**Comment by peteruithoven** [comment]
That would be interesting! That would enable running it on OpenWRT devices too.

**Comment by rauchg** [comment]
If you can use C++, look at: https://github.com/socketio/socket.io-client-cpp
