### ISSUE TITLE
Sending to all in group, including sender...

### ISSUE THREAD

**Issue by varmint09** [Automattic/socket.io#2082]
Hello,

I almost have it all working, as I dropped Primus support, but for some reasonn room messages do not get sent to the author, but the others in the room get the message.

I am using this code to send the message out to all people in a room, what am i doing wrong?

 socket.to(roomId).emit('message', { ' text' : 'failing!' }));

when room Id is the name of a group, so to repeat everyone but the sender gets this message, I have tried;

socket.broadcast.to
socket.in

Could someone help me out? Thanks!

**Comment by nkzawa** [comment]
`broadcast` works like that. You can use a namespace to send a message to all users in a room.

```js
io.of('/nsp').to(roomId).emit('message', 'hello');
```
