### ISSUE TITLE
Safari 8 Websocket upgrade issue

### ISSUE THREAD

**Issue by mmilleruva** [Automattic/socket.io#2086]
I am seeing some strange behavior in the socketio debug logs when using Safari. It looks like socket.io is unable to upgrade to websockets. If I specify `transports: ['websocket']`when creating a new socket, Safari is never able to connect, while Chrome is unaffected. Here is a copy of the log output I am seeing
![safari-socketio-issue](https://cloud.githubusercontent.com/assets/3188747/7192137/d7ba32b0-e460-11e4-862a-35e709aa5e88.png)

**Comment by nkzawa** [comment]
I couldn't reproduce this. How can we reproduce?

**Comment by mmilleruva** [comment]
It looks like this was fixed in 1.3.5. I was seeing this issue in 1.3.3
