### ISSUE TITLE
No event on disconnect

### ISSUE THREAD

**Issue by godicked** [Automattic/socket.io#2088]
Sometimes the disconnect even does not trigger.
It does not trigger if i activate flight mode on mobile. I cant detect the disconnection on client side, but the server doesnt get an event.. the socket is still connected on server side and dont leave rooms

Example : 
server
```javascript
var express = require('express');
var app = express();

app.use(express.static(__dirname + '/public'));

var server = require('http').createServer(app);
var io = require('socket.io').listen(server)

app.use("/public", express.static(__dirname + '/public'));

app.get('/', function (req, res) {
res.sendfile(__dirname + '/test.html');
});

io.sockets.on('connection', function (socket, pseudo) {
	console.log('connection');

	socket.on('disconnect',function(){
		console.log('disconnection');
	});
});
server.listen(8080);
```

client
```html
<!DOCTYPE html>
<html>
	<head>
	</head>
	<body>
		<script src="/socket.io/socket.io.js"></script>
		<script>
			var socket = io.connect();
		</script>
	</body>
</html>
```

Step 1 : connect to node server with mobile phone -> console logs 'connection'
Step 2 : flight mode -> console logs nothing
Step 3 : remove flight mode -> console logs 'connection'

Disconnect event never happens

**Comment by nkzawa** [comment]
Socket.io checks the status of a socket for this kind of cases at intervals of a minute or so (depends on settings).
Can you see whether `disconnect` event is fired if you wait a few minutes?

**Comment by godicked** [comment]
Yes you are right, thank you for the information.
Before i close the issue can you tell me where i can change thoses settings ?

**Comment by nkzawa** [comment]
@godicked Please see `pingTimeout` and `pingInterval` https://github.com/Automattic/engine.io#methods-1

You can pass these options through constructor on socket.io too.
