### ISSUE TITLE
SocketIO emit with callback fails while upgrading 0.9.16 to 1.35

### ISSUE THREAD

**Issue by tonyjose009** [Automattic/socket.io#2101]
Hi,

In 0.9.16,  I use socket.emit with callback so that the chat server return some data and I can handle the result as per the acknowledgement. But after the upgrade to 1.35 I've found a error in console like this

Uncaught TypeError: Cannot read property 'apply' of undefined.

I've done something like this,

From web
```js
            socket.emit('userToUser', { 'usename': 'John',
                'message': 'hi'
            }, function(callback){
                //callback handled    
            });
```
Chat Server
```js
    socket.on('userToUser', function(content, callback){
        //do something
        if(callback) return callback({'result':'success', 'messageid':content.messageid,        'chatid':content.chatid});
    });
```

**Comment by tonyjose009** [comment]
When I removed the callback from client side, there is no error. So I believe there will be some changes to be done in the callback,    please help

**Comment by nkzawa** [comment]
I'm not sure about v0.9, but on v1.x, you can't accept a function as an argument on ack callback.

**Comment by tonyjose009** [comment]
So how is it possible to manage server acknowledgement(success/failure) in client side ?

**Comment by nkzawa** [comment]
You can get an acknowledgement from the server anyway. Isn't it enough for you?

```js
socket.emit('userToUser', { 'usename': 'John',
  'message': 'hi'
}, function(data){
   console.log(data);
    // prints {'result': 'success', 'messageid': messageid, 'chatid': chatid}    
});
```

**Comment by tonyjose009** [comment]
See I'm getting the callback and  the chat  is working.
But my concern is about the error.

Uncaught TypeError: Cannot read property 'apply' of undefined.

which points to  socketio.js

/**
 * Called upon a server acknowlegement.
 *
 * @param {Object} packet
 * @api private
 */

Socket.prototype.onack = function(packet){
  debug('calling ack %s with %j', packet.id, packet.data);
  var fn = this.acks[packet.id];
  fn.apply(this, packet.data);
  delete this.acks[packet.id];
};

**Comment by nkzawa** [comment]
How can we reproduce the error?

**Comment by tonyjose009** [comment]
Issue fixed guys,
Thanks for  your comments. 

See this http://stackoverflow.com/questions/29935861/socketio-emit-with-callback-fails-while-upgrading-0-9-16-to-1-3-5/30045575#30045575
