### ISSUE TITLE
can we get a release ?

### ISSUE THREAD

**Issue by stefanpenner** [Automattic/socket.io#2107]
The current released version does not have an optional dependency on the native extension introduced by `ws`.

**Comment by stefanpenner** [comment]
ping

**Comment by thomassuckow** [comment]
Bump

**Comment by shinnn** [comment]
When?

**Comment by rauchg** [comment]
I'm on it!

**Comment by stefanpenner** [comment]
:dancers:

**Comment by stefanpenner** [comment]
@rauchg friendly reminder

**Comment by jrjohnson** [comment]
:+1:

**Comment by shinnn** [comment]
Publishing a new version would also fix https://github.com/Automattic/socket.io/issues/2149.

**Comment by felixrieseberg** [comment]
Yeah, we at Microsoft would love to see a new version :+1: Let me know if there's anything I can do to help.

**Comment by stefanpenner** [comment]
@rauchg friendly reminder

**Comment by jeffshaver** [comment]
Would be sweet if we could get a release for this

**Comment by pacarole** [comment]
:+1:

**Comment by bushong1** [comment]
:+1:

**Comment by jeffshaver** [comment]
:+1:

**Comment by jonnii** [comment]
:+1:

**Comment by jrjohnson** [comment]
For anyone else watching this thread 1.3.6 has been released.

**Comment by felixrieseberg** [comment]
cc @stefanpenner 

![](http://media.giphy.com/media/10xZU9b7JBx14s/giphy.gif)

**Comment by rauchg** [comment]
Thanks guys! Updated every other thread but not this one.
http://socket.io/blog/socket-io-1-3-6/#

I was busy with P2P among other things, and of course `1.4.0` which is very very close!

**Comment by stefanpenner** [comment]
:+1:
