### ISSUE TITLE
send message to specific user identified by our app's userid

### ISSUE THREAD

**Issue by eisneim** [Automattic/socket.io#2121]
there is no documentation on how to send message to specific socket, even this one 
```javascript
socket.broadcast.to(id).emit('my message', msg);
```
is hidden is some secret place!!!

my old hacky solution is store connected  socket to a big object map in memory , which is bad:
```javascript

var scoketCons = {};

io.of('/onlyForManagers').on('connection',function(socket){
    /*  after do some verification */
   blah blah blah.....
  scoketCons[  user._id  ] = [ socket  ] // must be array , cause he/she might open more than on browser tab

})
```
now in any route of our Koa or Express app, use `scoketCons[user._id].emit()` can send to a specific user

but , this is bad, it cause memory leak, i wanted to store socket in redis, but not sure if it works;

so , what is the "official" way of doing this?

**Comment by eisneim** [comment]
ok , i get it, each socket is accutally a room, i didn't realize that; so to send to a specific user, first we have to make this user join a room just for himself
```javascript
socket.join(user._id);
//then
io.to( user._id ).emit('some event'):
```

socket.io is good, i have to say, the documentation sucks!!
a lot of method, option  and function are not documented!

**Comment by peteruithoven** [comment]
Hi elsnelm, I agree, but let's keep it friendly. 
There is an issue to improve the documentation: https://github.com/Automattic/socket.io/issues/2020
This also mentions a community effort to start a seperate doc repo: https://github.com/alejonext/doc-socketio

A user is automatically added to a room (I wouldn't say it *is* a room). This room has the socket's id (created by socket.io). I think you're approach is nice, not sure if there is a official way.
