### ISSUE TITLE
Why there's no bower for socket.io.js?

### ISSUE THREAD

**Issue by leonprou** [Automattic/socket.io#2122]
I'm using socket.io in my Cordova app.

In the [tutorial] (http://socket.io/socket-io-with-apache-cordova/) you're suggesting to load socket.io from cdn for the client. I much prefer it to come packed with my app as rest of my dependencies, much natural for Cordova.

**Comment by jordanpappas** [comment]
There is a bower for the socket.io-client. Just try 

bower install socket.io-client --save

**Comment by leonprou** [comment]
My bad
