### ISSUE TITLE
cdn.socket.io has an out of date certificate.

### ISSUE THREAD

**Issue by hako** [Automattic/socket.io#2131]
I've been getting this error in the javascript console.

``Failed to load resource: The certificate for this server is invalid. You might be connecting to a server that is pretending to be “cdn.socket.io” which could put your confidential information at risk.```

I've looked at the `https://cdn.socket.io` certificate and it just expired here in the UK. (10:00AM BST)

![expired_cert](https://cloud.githubusercontent.com/assets/2040416/7832767/74179c20-0459-11e5-9dcd-f5fe63e89bb8.png)

Any chance of an update to the certificate on the cdn?

**Comment by BenjaminJWilliams** [comment]
Can confirm that it expired at 5:00 AM EST.

**Comment by e-gnat** [comment]
I have the same problem with my ionic app, and worst of all I can't change it for local file - some why it's not working

**Comment by alexgerv** [comment]
+1 I have the same error.

**Comment by llaakso** [comment]
+1

I can see that some of our users is suffering from this as well.

**Comment by e-gnat** [comment]
"+1

I can see that some of our users is suffering from this as well."

If them have it in cash as it can work

**Comment by jossi** [comment]
Same here
Only way to resolve was to download the non https version from http://cdn.socket.io/socket.io-1.3.4.js and host the script locally

**Comment by BenjaminJWilliams** [comment]
Actually, I believe the non-https version is still working so in the mean time you can fall back to http://cdn.socket.io/socket.io-1.3.4.js unless you absolutely require HTTPS.

**Comment by hako** [comment]
Just checked the certificate now and it's valid again :+1:

**Comment by guigusman** [comment]
I'm having the same error again today. Exactly one year later. Are you guys renewing the certificate?

**Comment by renatogiuliani** [comment]
Certificate has expired again today: ‎
Valid to: Friday, ‎May 27. ‎‎2016 5:00:54pm..

great way to start a weekend ;-)

**Comment by trsreagan3** [comment]
same here

**Comment by guigusman** [comment]
I've switched it to cloudfare meanwhile, just point to your version.
https://cdnjs.cloudflare.com/ajax/libs/socket.io/1.2.0/socket.io.min.js

For a production environment like mine, it was the best option.

**Comment by sentient** [comment]
Same here. Hosting with this CDN is not a production ready solution

**Comment by ivansf** [comment]
+1

**Comment by sentient** [comment]
@guigusman thanks for the cloudflare link. A quick fix just before the weekend. But long term I will host myself.

**Comment by MasterJames** [comment]
Letsencrypt.org means this should never happen again.

**Comment by danielbeardsley** [comment]
You should probably just stop providing your own CDN if keeping the ssl cert from expiring is not something you can commit to doing. Otherwise you're damaging the image of the product.

**Comment by MasterJames** [comment]
Maybe look again at letsencrypt.org ? ! Free and automated with pretty easy setup.

**Comment by gabrieledarrigo** [comment]
Come on un guys!

**Comment by rauchg** [comment]
I reached out to Automattic for them to fix it (they host the CDN). Not much I can do on my end. Sorry everyone!
