### ISSUE TITLE
Error: Cannot find module '../..'

### ISSUE THREAD

**Issue by 1mihirpandya** [Automattic/socket.io#2148]
When I run the index.js file, there is a line of code that says "var io = require('../..')(server);". This code causes an error for me (picture attached below). How would I fix this problem?
![screen shot 2015-06-06 at 1 48 48 pm](https://cloud.githubusercontent.com/assets/7907525/8021440/e9bcba2a-0c54-11e5-827a-1d5e90e50836.png)

**Comment by dev0x10** [comment]
You cannot do that require('.../..')
You have to write the filename you want to require

**Comment by sksq** [comment]
var io = require('../..')(server);

This statement expects "socket.io" be installed at 2 levels up your directory. But as it seems by your error messages, it can't find "socket.io"

You can simply type in terminal: 
     npm install socket.io --save
This will install socket and then replace "../.." with "socket.io"
