### ISSUE TITLE
Is there anyway to listen to ping event from engine.io?

### ISSUE THREAD

**Issue by dytsai** [Automattic/socket.io#2153]
In our application, I want to monitor if client is still alive. I know heartbeat is handled by engine.io and we can set its pingInterval and pingTimeout when initializing socket.io. So it seems that the best way is to set up a "alive" flag when receiving ping event. However, how can I listen to ping event?

**Comment by nkzawa** [comment]
You can just check whether the connection is still alive instead, since the connection will be forced close when ping timeout.
