### ISSUE TITLE
socket.emit event for only the current user doesn't fire

### ISSUE THREAD

**Issue by flashios09** [Automattic/socket.io#2168]
I'm using socket.io and when i want to emit an event from the server to client **only for the connected user** it doesn't work !
I don't have an error or any response :(
Thats my code
```js
// Server.js
var server     = require('http').createServer(),
    io         = require('socket.io')(server),
    logger     = require('winston'),
    port       = 1337;

// Logger config
logger.remove(logger.transports.Console);
logger.add(logger.transports.Console, { colorize: true, timestamp: true });
logger.info('SocketIO > listening on port ' + port);

io.on('connection', function (socket){
    logger.info('SocketIO > Connected socket ' + socket.id);

    socket.on('ElephantIO.login', function (user){
        socket.emit('SocketIO.login', user);
    });

    socket.on('disconnect', function () {
        logger.info('SocketIO > Disconnected socket ' + socket.id);
    });
});

server.listen(port);
```
```js
// Client.js
(function() {
    var socket = io.connect('http://localhost:1337');

    socket.on('SocketIO.login', function(user) {
        console.log(user);
        alert('SocketIO.login');
    });

})();
```
If i change the ```socket.emit('SocketIO.login', user);``` with ```socket.broadcast.emit('SocketIO.login', user);``` to emit this event to the **all other connected user** it works

If i change the ```socket.emit('SocketIO.login', user);``` with ```io.emit('SocketIO.login', user);``` to emit this event to the **all connected user** i have the same behavior of the ```socket.broadcast.emit('SocketIO.login', user);```

Always the **current user window** don't have a response or an error !

**Comment by maxzeroedge** [comment]
Try using io.sockets.emit

**Comment by flashios09** [comment]
@maxzeroedge I tried ```io.sockets.emit```, it works like ```io.emit``` or ```socket.broadcast.emit```, always **the current connected user** hasn't any response or an error, the event will be fired only on **the other window** !

**Comment by maxzeroedge** [comment]
It worked when I was using in a separate project. Does socket.emit send an event to the client? 
Just for sake of checking, did you try socket.emit and socket.broadcast.emit together and get the desired response?

**Comment by flashios09** [comment]
@maxzeroedge I think that you didn't understand my problem, lets say that we have three browser window, so we have three socket **A,B and C**.
If we want to emit an event to all three sockets **A,B and C** we use ```io.emit``` or ```io.sockets.emit```
If **A** emit an event from **Client.js** and we want to notify **B and C** we use ```socket.broadcast.emit```
If **A** emit an event from **Client.js** and we want to do something with **Server.js** and re-emit an event to **Client.js** only for **A** we use ```socket.emit``` not ```socket.broadcast.emit``` or ```io.emit|io.sockets.emit```.
For me when i use ```socket.emit``` from **Server.js** to **Client.js** it didn't work ! I don't have a response or an error, just nothing ! When i use ```socket.broadcast.emit``` it works, when i use ```io.emit``` socket **A** doesn't have a response and socket **B and C** have the response(like we use ```socket.broadcast.emit```

**Comment by aklatt1194** [comment]
I am having a similar issue... socket.emit does not seem to work in some cases. The socket is still supposedly connected (according to the socket.connected property), and I can receive messages from the client, I just cannot send to the client with socket.emit. All attempts to broadcast(io.emit, io.sockets.emit, socket.broadcast.emit) send to all of the other clients but not to the client associated with the socket of interest. It is as if the connection is closed in one direction...

**Comment by sasankh** [comment]
I might be asking a silly question but what is 'ElephantIO.login' for, I don't see it in the client side.

**Comment by flashios09** [comment]
@sasankh I use ElephantIO to emit an event from a Php script. Sorry my problem isn't coming from socketIO but from my script. I emit an event then i have a redirection to another page that's why i loose(disconnected socket) the current socket and i don't have a response or an error with the current window.
