### ISSUE TITLE
Http instead of Ws protocol

### ISSUE THREAD

**Issue by iamdriz** [Automattic/socket.io#2180]
According to the docs: http://socket.io/docs/

You set the protocol to `http` e.g. `var socket = io('http://localhost');`

But should it not be `ws` e.g. `var socket = io('ws://localhost');`

**Comment by sasankh** [comment]
as far as i know. you should be able to use 'ws' if you want. The only reason I can think is that 'ws' is not supported in all browser. But the major browser like chrome, firefox, opera, safari has support for it.

**Comment by maxzeroedge** [comment]
As far as I know, socket.io has fallbacks for cases where sockets are not
supported out of the box. Hence, we use http:// instead of ws://
